// Generated by BugReel Chrome extension 0.1.0 from recording 9085a05f-5a87-44c4-963c-f45fd6dfcaf5 (schema v1).
//
// STATUS: UNVERIFIED DRAFT. BugReel has not run this test. It does not confirm that the bug reproduces.
// Playwright draft status: draft.
//
// Report: Checkout fails after applying a coupon
// Start URL: http://127.0.0.1:4173/app.html
//
// Notes:
// - Typed values were omitted. Set the listed BUGREEL_VALUE_* environment variables before running the draft.
// - The draft starts from a fresh browser context. Sign-in state, cookies, and storage that existed before recording are not captured; configure authentication (for example storageState) if the page needs it.
// - The generated assertion checks that the selected failure still occurs. It passes while the bug is present; it is not a fix verification.
//
// Required configuration before running:
// - BUGREEL_VALUE_1: Enter [value not recorded] in Coupon code (typed-value recording was off for this session)
// - BUGREEL_VALUE_2: Enter [password omitted] in Password (password field; the value is never recorded)
// - BUGREEL_VALUE_3: Select [value not recorded] in Size (typed-value recording was off for this session)

import { test, expect } from '@playwright/test';

function requiredValue(name: string): string {
  const value = process.env[name];
  if (value === undefined) throw new Error(`Set the ${name} environment variable before running this BugReel draft. See the configuration notes at the top of this file.`);
  return value;
}

test.use({ viewport: { width: 1200, height: 900 } });

test("Checkout fails after applying a coupon (BugReel unverified draft)", async ({ page }, testInfo) => {
  // Recorded failure: POST /api/fail returned HTTP 500.
  const failureResponse = page.waitForResponse(response => response.request().method() === "POST" && new URL(response.url()).pathname === "/api/fail" && response.status() === 500).catch(() => null);

  try {
    await test.step("1. Open /app.html", async () => {
      await page.goto("http://127.0.0.1:4173/app.html");
    });
    await test.step("2. Enter [value not recorded] in Coupon code", async () => {
      await page.getByRole("textbox", { name: "Coupon code", exact: true }).fill(requiredValue("BUGREEL_VALUE_1"));
    });
    await test.step("3. Enter [password omitted] in Password", async () => {
      await page.getByLabel("Password", { exact: true }).fill(requiredValue("BUGREEL_VALUE_2"));
    });
    await test.step("4. Select [value not recorded] in Size", async () => {
      await page.getByRole("combobox", { name: "Size", exact: true }).selectOption(requiredValue("BUGREEL_VALUE_3"));
    });
    await test.step("5. Click Accept terms", async () => {
      await page.getByRole("checkbox", { name: "Accept terms", exact: true }).click();
    });
    await test.step("6. Click Checkout", async () => {
      await page.getByTestId("checkout").click();
    });
    await test.step("Check the recorded failure signature (passes while the bug is present)", async () => {
      const response = await failureResponse;
      expect(response, "Expected POST /api/fail to return HTTP 500, as recorded").not.toBeNull();
    });
  } finally {
    await testInfo.attach('bugreel-final-page', { body: await page.screenshot({ fullPage: true }).catch(() => Buffer.from('')), contentType: 'image/png' });
  }
});
