import type { BugReelRecording, RecordingAction } from './recording';
import { networkSignatureTarget, signatureText, triggerActionIndex } from './recording';
import { comment, literal, locatorSource, plain } from './source';

const I2 = '  ';
const I4 = '    ';
const I6 = '      ';

function valueSource(action: RecordingAction) {
  return action.configKey ? `requiredValue(${literal(action.configKey)})` : literal(action.value ?? '');
}

function waitForUrlSource(url: string) {
  const parsed = new URL(url);
  if (!parsed.search && !parsed.hash && !url.includes('REDACTED')) return `await page.waitForURL(${literal(url)});`;
  // Query strings and fragments often vary between runs, and redacted values cannot match; compare the path only.
  return `await page.waitForURL(url => url.pathname === ${literal(parsed.pathname)});`;
}

function actionSource(action: RecordingAction): string[] {
  const lines: string[] = [];
  if (action.selector?.confidence === 'fallback') lines.push('// Low-confidence positional selector. Review it before running.');
  if (action.url?.includes('REDACTED')) lines.push('// This URL contains redacted values. Replace REDACTED with a real value if the page requires it.');
  switch (action.type) {
    case 'goto': lines.push(`await page.goto(${literal(action.url!)});`); break;
    case 'waitForURL': lines.push(waitForUrlSource(action.url!)); break;
    case 'reload': lines.push('await page.reload();'); break;
    case 'click': lines.push(`await ${locatorSource(action.selector!, literal)}.click();`); break;
    case 'fill': lines.push(`await ${locatorSource(action.selector!, literal)}.fill(${valueSource(action)});`); break;
    case 'select': lines.push(`await ${locatorSource(action.selector!, literal)}.selectOption(${valueSource(action)});`); break;
    case 'press': lines.push(`await ${locatorSource(action.selector!, literal)}.press('Enter');`); break;
  }
  return lines;
}

type TimelineItem = { at: number; order: number; lines: string[] };

/**
 * Generates an editable Playwright test from a validated recording. The output is always an UNVERIFIED draft:
 * BugReel does not execute it, and nothing in the source claims that the bug was reproduced.
 */
export function generatePlaywright(recording: BugReelRecording): string {
  const { report, playwright } = recording;
  const signature = recording.evidence.failureSignature;
  const failure = signature && playwright.assertion === 'failure-signature'
    ? [...recording.evidence.console, ...recording.evidence.network].find(item => item.id === signature.evidenceId)
    : undefined;

  const header = [
    comment(`Generated by ${plain(recording.generator.name, 100)} ${plain(recording.generator.version, 40)} from recording ${recording.session.id} (schema v${recording.schemaVersion}).`),
    '//',
    '// STATUS: UNVERIFIED DRAFT. BugReel has not run this test. It does not confirm that the bug reproduces.',
    `// Playwright draft status: ${playwright.status}.`,
    '//',
    comment(`Report: ${plain(report.title, 200)}`),
    comment(`Start URL: ${recording.target.startUrl}`),
    '//',
    '// Notes:',
    ...playwright.notes.map(note => comment(`- ${plain(note, 500)}`)),
  ];
  if (recording.requiredConfiguration.length) {
    header.push('//', '// Required configuration before running:');
    for (const entry of recording.requiredConfiguration) header.push(comment(`- ${entry.key}: ${plain(entry.description, 300)}`));
  }

  // Failure observation starts immediately before the step that most likely triggered the recorded failure, so an
  // unrelated earlier failure (or one from another origin with the same path) cannot satisfy the check.
  const setup: string[] = [];
  const checks: string[] = [];
  if (failure && (failure.kind === 'http' || failure.kind === 'transport')) {
    const target = networkSignatureTarget(failure.url)!;
    const where = `${failure.method} ${target.origin}${target.pathname}`;
    const matchUrl = (variable: string) => `${variable}.origin === ${literal(target.origin)} && ${variable}.pathname === ${literal(target.pathname)}`;
    if (failure.kind === 'http') {
      setup.push(
        comment(`Recorded failure: ${where} returned HTTP ${failure.status}. Only this origin, path, method, and status match.`, I4),
        `${I4}const failureResponse = page.waitForResponse(response => { const url = new URL(response.url()); return response.request().method() === ${literal(failure.method)} && ${matchUrl('url')} && response.status() === ${failure.status}; }).catch(() => null);`,
      );
      checks.push(`${I4}const response = await failureResponse;`, `${I4}expect(response, ${literal(`Expected ${where} to return HTTP ${failure.status}, as recorded`)}).not.toBeNull();`);
    } else {
      setup.push(
        comment(`Recorded failure: ${where} failed (${plain(failure.error || 'network error', 120)}). Only this origin, path, and method match.`, I4),
        `${I4}const failedRequests: { method: string; url: string }[] = [];`,
        `${I4}page.on('requestfailed', request => failedRequests.push({ method: request.method(), url: request.url() }));`,
      );
      checks.push(`${I4}await expect.poll(() => failedRequests.some(request => { const url = new URL(request.url); return request.method === ${literal(failure.method)} && ${matchUrl('url')}; }), { message: ${literal(`Expected ${where} to fail, as recorded`)} }).toBe(true);`);
    }
  } else if (failure && (failure.kind === 'console' || failure.kind === 'exception')) {
    const text = signatureText(failure.message)!;
    if (failure.kind === 'console') {
      // Recordings from earlier versions have no consoleType; they only ever recorded console.error.
      const type = failure.consoleType ?? 'error';
      setup.push(comment(`Recorded failure: a console.${type} message containing the text below.`, I4), `${I4}const consoleMessages: string[] = [];`, `${I4}page.on('console', message => { if (message.type() === ${literal(type)}) consoleMessages.push(message.text()); });`);
      checks.push(`${I4}await expect.poll(() => consoleMessages.some(text => text.includes(${literal(text)})), { message: ${literal(`Expected the recorded console.${type} message`)} }).toBe(true);`);
    } else {
      setup.push(comment('Recorded failure: an uncaught exception containing the text below.', I4), `${I4}const pageErrors: string[] = [];`, `${I4}page.on('pageerror', error => pageErrors.push(error.message));`);
      checks.push(`${I4}await expect.poll(() => pageErrors.some(text => text.includes(${literal(text)})), { message: 'Expected the recorded uncaught exception' }).toBe(true);`);
    }
  }

  const timeline: TimelineItem[] = [];
  const trigger = failure ? triggerActionIndex(recording.actions, failure.elapsedMs) : -1;
  recording.actions.forEach((action, index) => {
    const body = actionSource(action).map(line => `${I6}${line}`).join('\n');
    const step = [`${I4}await test.step(${literal(`${index + 1}. ${action.label}`)}, async () => {`, body, `${I4}});`];
    timeline.push({ at: action.elapsedMs, order: 1, lines: index === trigger && setup.length ? [...setup, ...step] : step });
  });
  if (setup.length && trigger === -1) timeline.push({ at: -1, order: 0, lines: setup });
  recording.unsupportedSteps.forEach(step => timeline.push({ at: step.elapsedMs, order: 0, lines: [comment(`UNSUPPORTED STEP (not replayed, ${step.reason}): ${plain(step.description, 250)}`, I4)] }));
  recording.gaps.forEach((gap, index) => timeline.push({
    at: gap.startElapsedMs, order: 0,
    lines: [comment(`RECORDING GAP ${index + 1}: recording was paused${gap.endedAt ? '' : ' and not resumed'}. Actions performed during the pause were not captured.`, I4), `${I4}// Add the missing steps here.`],
  }));
  timeline.sort((a, b) => a.at - b.at || a.order - b.order);

  const body: string[] = [];
  if (recording.gaps.length) body.push(`${I2}test.fixme(true, ${literal('BugReel: this recording has gaps. Add the missing steps marked RECORDING GAP, then remove this line.')});`, '');
  body.push(`${I2}try {`);
  body.push(...timeline.flatMap(item => item.lines));
  if (checks.length) {
    body.push(`${I4}await test.step(${literal('Check the recorded failure signature (passes while the bug is present)')}, async () => {`, ...checks.map(line => `${I2}${line}`), `${I4}});`);
  } else {
    body.push(`${I4}// TODO: no assertion was generated. Add an assertion that fails or passes based on the reported behaviour.`);
    if (report.actual.trim()) body.push(comment(`Actual behaviour reported: ${plain(report.actual, 400)}`, I4));
    if (report.expected.trim()) body.push(comment(`Expected behaviour reported: ${plain(report.expected, 400)}`, I4));
  }
  body.push(`${I2}} finally {`, `${I4}await testInfo.attach('bugreel-final-page', { body: await page.screenshot({ fullPage: true }).catch(() => Buffer.from('')), contentType: 'image/png' });`, `${I2}}`);

  const viewport = recording.target.viewport;
  const helper = recording.requiredConfiguration.some(entry => entry.key.startsWith('BUGREEL_VALUE_')) ? [
    '',
    'function requiredValue(name: string): string {',
    '  const value = process.env[name];',
    "  if (value === undefined) throw new Error(`Set the ${name} environment variable before running this BugReel draft. See the configuration notes at the top of this file.`);",
    '  return value;',
    '}',
  ] : [];

  return [
    ...header,
    '',
    "import { test, expect } from '@playwright/test';",
    ...helper,
    '',
    ...(viewport ? [`test.use({ viewport: { width: ${viewport.width}, height: ${viewport.height} } });`, ''] : []),
    `test(${literal(`${plain(report.title, 160)} (BugReel unverified draft)`)}, async ({ page }, testInfo) => {`,
    ...body,
    '});',
    '',
  ].join('\n');
}
