import type { Session } from '@/lib/session';
import { Icon } from './icon';

const time = (ms: number) => `+${(ms / 1000).toFixed(2)}s`;
export function EvidencePanel({ session }: { session: Session }) {
  return <div className="evidence-grid">
    <section className="panel"><div className="panel-heading"><div className="panel-title"><Icon name="network" /><h2>Network evidence</h2><span className="count-badge">{session.networkErrors.length}</span></div><span className="panel-caption">HTTP + transport</span></div><div className="evidence-content">{session.networkErrors.length ? session.networkErrors.map(item => <article className="network-entry" key={item.id}><div className="network-entry-head"><span className="http-code">{item.status || 'ERR'}</span><strong className="mono">{item.method}</strong><span className="evidence-time">{time(item.elapsedMs)}</span></div><p className="network-path mono">{new URL(item.url).pathname}</p>{item.code && <p className="failure-code">{item.code}</p>}{item.error && <p className="failure-code">{item.error}</p>}<p className="evidence-url" title={item.url}>{item.url}</p></article>) : <div className="evidence-empty"><Icon name="check" size={20} /><span>No failed requests or HTTP errors captured.</span></div>}</div></section>
    <section className="panel"><div className="panel-heading"><div className="panel-title"><Icon name="terminal" /><h2>Console evidence</h2><span className="count-badge">{session.consoleErrors.length}</span></div><span className="panel-caption">Errors + exceptions</span></div><div className="evidence-content">{session.consoleErrors.length ? session.consoleErrors.map(item => <article className="console-entry" key={item.id}><div className="console-entry-head"><span className="error-label"><Icon name="close" size={12} />{item.type === 'pageerror' ? 'UNCAUGHT EXCEPTION' : 'CONSOLE.ERROR'}</span><span className="evidence-time">{time(item.elapsedMs)}</span></div><p className="mono">{item.message}</p>{item.url && <span className="evidence-url" title={item.url}>{new URL(item.url).pathname}{item.line !== undefined ? `:${item.line + 1}` : ''}</span>}</article>) : <div className="evidence-empty"><Icon name="check" size={20} /><span>No console errors or page exceptions captured.</span></div>}</div></section>
  </div>;
}
